### ISSUE TITLE
add anchor tags to metadata sections for easier linking

### ISSUE THREAD

**Issue by atn38** [PASTAplus/DataPortal#71]
Hello,

It'd be nice if the full metadata display had anchor tags so I can link to one particular section like this: `https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-ble.13.1#methods`. 

Motivation: I find myself telling researchers to "go to the landing page, click on View Full Metadata, scroll down and expand the Methods section". 

Desired effect: when user clicks on link, they are brought to the section already expanded, i.e. they don't need to toggle the button.

**Comment by servilla** [comment]
Hi @atn38, this is a great idea! I'll do some experimentation to see how this would best be implemented. I assume you are asking this for all main sections of the metadata page?

**Comment by atn38** [comment]
Hi Mark, yes, I suppose it's not too bad to add them all once you get in
there. If you can generate anchors for each of the data entities that may
be useful as well.

**Comment by servilla** [comment]
Interestingly, this resolution required javascript on document load to expand all collapsed fields since the page anchors would not automatically go to or expand the collapsed sections. The only drawback to this solution is that all of the collapsed sections are expanded, but only if there is a page anchor in the URL; otherwise, the full metadata page is collapsed by default - business as usual.

Here is an example URL: https://portal-d.edirepository.org/nis/metadataviewer?packageid=knb-lter-ble.17.5#methods

The following id selectors (and their corresponding sections) are now active and can be used as page anchors:
1. entities (Data Entities)
2. rights (Data Package Usage Rights)
3. annotations (External Annotations)
4. keywords (Keywords)
5. methods (Methods and Protocols)
6. people (People and Organizations)
7. coverage (Temporal, Geographic, and Taxonomic Coverage)
8. project (Project)
9. maintenance (Maintenance)
10. info (Additional Information)
11. additional (Additional Metadata)

**Comment by servilla** [comment]
OK, I did figure out how to expand only the section of interest and then scroll the view port to it.

**Comment by atn38** [comment]
This is great, thanks Mark. I'm seeing just the anchored section that's
expanded. All others are collapsed as usual. Great solution! I hope this is
useful for people.

**Comment by servilla** [comment]
Hi @atn38 this enhancement is now deployed on all production, staging, and development systems.
